### ISSUE TITLE
Reason for using rake task and not rails dbconsole

### ISSUE THREAD

**Issue by tejasbubane** [mattbrictson/pgcli-rails#1]
I was expecting to have `rails dbconsole` fire up `pgcli` and found out that the gem did exactly  the same before [this](https://github.com/mattbrictson/pgcli-rails/commit/6cc6f483a4a44611021441c43b2f4f20c298d97c) commit. 

Could not find the reason for the switch in the commit message, hence this issue.

**Comment by mattbrictson** [comment]
Good question. Basically, I rewrote it as a Rake task because:

1. Being a separate task allows you to explicitly opt-in. This is useful because not every developer on team, nor every environment (e.g. production) necessarily has the `pgcli` binary installed.
2. A Rake task seems less prone to bugs and future Rails incompatibilities than a monkey patch.

That being said, this is a young project and it can be rewritten again. I'm interested in your hearing suggestions!

**Comment by tejasbubane** [comment]
Those seem pretty valid reasons. Unfortunately I don't see any better way to tackle them. I think I should close this issue then.
